// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnaU-UMb4Pr0cd6yJt_Dtij5PbfTfWsAA',
    appId: '1:139209525842:web:99e49f3cfe61bddb042d8b',
    messagingSenderId: '139209525842',
    projectId: 'inventoryapp-21163',
    authDomain: 'inventoryapp-21163.firebaseapp.com',
    databaseURL: 'https://inventoryapp-21163-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventoryapp-21163.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfpHoK1nMQAiHq3f9IBT_jSJVbN93CjmY',
    appId: '1:139209525842:android:e12851bcffab644c042d8b',
    messagingSenderId: '139209525842',
    projectId: 'inventoryapp-21163',
    databaseURL: 'https://inventoryapp-21163-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inventoryapp-21163.appspot.com',
  );
}